
export const BEGIN_FETCH = 'BEGIN_FETCH';

export const CLOSE_CARD = 'CLOSE_CARD';

export const GET_BUSINESSES = 'GET_BUSINESSES';
export const GET_BUSINESSES_ERROR = 'GET_BUSINESSES_ERROR';
export const GET_BUSINESSES_SUCCESS = 'GET_BUSINESSES_SUCCESS';

export const SELECT_BUSINESS_MARKER = 'SELECT_BUSINESS_MARKER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_ SUCCESS';
