
export const BEGIN_FETCH = 'BEGIN_FETCH';

export const CLOSE_CARD = 'CLOSE_CARD';

export const DELETE_BUSINESS_ERROR = 'DELETE_BUSINESS_ERROR';
export const DELETE_BUSINESS_SUCCESS = 'DELETE_BUSINESS_SUCCESS';

export const GET_BUSINESSES = 'GET_BUSINESSES';
export const GET_BUSINESSES_ERROR = 'GET_BUSINESSES_ERROR';
export const GET_BUSINESSES_SUCCESS = 'GET_BUSINESSES_SUCCESS';

export const SELECT_BUSINESS_MARKER = 'SELECT_BUSINESS_MARKER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SET_JWT = 'SET_JWT';

export const SAVE_BUSINESS_ERROR = 'SAVE_BUSINESS_ERROR';
export const SAVE_BUSINESS_SUCCESS = 'SAVE_BUSINESS_SUCCESS';
